export type CardProduct = {
  name: string;
  issuer: string;
  country: "USA" | "India" | "UK" | "Global";
  type: "Credit" | "Debit";
  network: "Visa" | "Mastercard" | "American Express" | "Discover" | "RuPay";
  slug: string;
  bestFor: string;
  annualFee: string;
  creditProfile: string;
  rewardStyle: string;
  highlights: string[];
  pros: string[];
  cons: string[];
  criteria: string[];
  howToUse: string[];
  earnGuide?: string[];
  redeemGuide?: string[];
  bestSpendingPlaces?: string[];
  avoidIf: string;
  sourceUrl: string;
  color: string;
};

export const creditCards: CardProduct[] = [
  {
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "chase-sapphire-preferred",
    bestFor: "Travel rewards beginners who want flexible points and strong travel protections.",
    annualFee: "Paid annual fee",
    creditProfile: "Good to excellent credit usually expected",
    rewardStyle: "Flexible travel points",
    highlights: ["Travel and dining rewards", "Hotel credit through issuer travel portal", "Point transfers", "No foreign transaction fees"],
    pros: ["Flexible points ecosystem", "Strong beginner travel card", "Useful travel protections"],
    cons: ["Annual fee", "Portal credits require specific booking behavior", "Not ideal if you carry a balance"],
    criteria: ["You travel at least a few times per year", "You can pay in full", "You value points more than simple cashback"],
    howToUse: ["Use for dining and travel", "Compare portal vs transfer partner value", "Set autopay for statement balance"],
    avoidIf: "You want no-fee simplicity or usually carry credit card debt.",
    sourceUrl: "https://www.chase.com/sapphire-cards/personal/preferred",
    color: "from-slate-900 to-indigo-700"
  },
  {
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "chase-sapphire-reserve",
    bestFor: "Frequent travelers who can use premium travel credits, lounge access, and protections.",
    annualFee: "High annual fee",
    creditProfile: "Excellent credit usually expected",
    rewardStyle: "Premium flexible travel points",
    highlights: ["Premium travel benefits", "Airport lounge access", "Travel credits", "Point transfers"],
    pros: ["Strong travel insurance package", "Premium redemption options", "Useful for frequent travelers"],
    cons: ["High annual fee", "Benefits require active use", "Weak fit for occasional travelers"],
    criteria: ["You travel often", "You use credits without overspending", "You value lounge and insurance benefits"],
    howToUse: ["Track annual credits", "Book eligible travel strategically", "Use protections by paying trip costs with the card"],
    avoidIf: "You travel rarely or cannot offset the annual fee naturally.",
    sourceUrl: "https://www.chase.com/sapphire-cards/personal/reserve",
    color: "from-stone-950 to-neutral-600"
  },
  {
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "capital-one-venture-rewards",
    bestFor: "Travelers who want simple miles without managing many bonus categories.",
    annualFee: "Paid annual fee",
    creditProfile: "Good to excellent credit usually expected",
    rewardStyle: "Flat-rate travel miles",
    highlights: ["Simple travel miles", "Transfer partners", "Travel statement credit style redemptions", "No foreign transaction fees"],
    pros: ["Easy earning structure", "Good for mixed spending", "Flexible travel redemption"],
    cons: ["Annual fee", "Transfer values vary", "Less category optimization"],
    criteria: ["You want simple travel rewards", "Your spending is broad", "You redeem for travel"],
    howToUse: ["Use as everyday travel card", "Compare transfer vs statement redemption", "Avoid interest charges"],
    avoidIf: "You prefer pure cashback or no annual fee.",
    sourceUrl: "https://www.capitalone.com/credit-cards/venture/",
    color: "from-blue-950 to-sky-700"
  },
  {
    name: "Capital One Venture X",
    issuer: "Capital One",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "capital-one-venture-x",
    bestFor: "Premium travelers who can use portal credits and lounge benefits.",
    annualFee: "High annual fee",
    creditProfile: "Excellent credit usually expected",
    rewardStyle: "Premium travel miles",
    highlights: ["Premium travel credits", "Lounge access", "Anniversary miles", "Flat-rate miles"],
    pros: ["Premium benefits can offset fee", "Simple earning", "Good international travel fit"],
    cons: ["Portal behavior required", "High fee", "Not for balance carriers"],
    criteria: ["You travel frequently", "You will use annual credits", "You want simple premium rewards"],
    howToUse: ["Use travel credits early", "Track lounge access rules", "Redeem miles for travel value"],
    avoidIf: "You do not want to book through issuer travel tools.",
    sourceUrl: "https://www.capitalone.com/credit-cards/venture-x/",
    color: "from-zinc-950 to-blue-800"
  },
  {
    name: "American Express Gold Card",
    issuer: "American Express",
    country: "USA",
    type: "Credit",
    network: "American Express",
    slug: "american-express-gold",
    bestFor: "High grocery and dining spenders who can use statement credits.",
    annualFee: "Paid annual fee",
    creditProfile: "Good to excellent credit usually expected",
    rewardStyle: "Membership rewards points",
    highlights: ["Dining rewards", "Supermarket rewards", "Transfer partners", "Statement credits"],
    pros: ["Strong food category value", "Flexible points", "Useful for urban spenders"],
    cons: ["Annual fee", "Credits require tracking", "Acceptance varies internationally"],
    criteria: ["You spend heavily on dining/groceries", "You use credits organically", "You understand points"],
    howToUse: ["Put food spending here", "Track monthly credits", "Redeem through high-value partners"],
    avoidIf: "You want one simple no-fee card.",
    sourceUrl: "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    color: "from-yellow-700 to-amber-300"
  },
  {
    name: "American Express Platinum Card",
    issuer: "American Express",
    country: "USA",
    type: "Credit",
    network: "American Express",
    slug: "american-express-platinum",
    bestFor: "Luxury travelers who can use multiple premium credits and lounge benefits.",
    annualFee: "Very high annual fee",
    creditProfile: "Excellent credit usually expected",
    rewardStyle: "Premium membership rewards",
    highlights: ["Airport lounge access", "Premium travel credits", "Hotel status style perks", "Transfer partners"],
    pros: ["High-end travel benefits", "Strong lounge ecosystem", "Premium purchase protections"],
    cons: ["Very high fee", "Complex credits", "Poor fit for casual travelers"],
    criteria: ["You fly often", "You track credits carefully", "You value premium travel comfort"],
    howToUse: ["Build a credit checklist", "Use for flights", "Transfer points intentionally"],
    avoidIf: "You dislike managing credits or travel rarely.",
    sourceUrl: "https://www.americanexpress.com/us/credit-cards/card/platinum/",
    color: "from-neutral-300 to-slate-600"
  },
  {
    name: "Blue Cash Preferred",
    issuer: "American Express",
    country: "USA",
    type: "Credit",
    network: "American Express",
    slug: "blue-cash-preferred",
    bestFor: "Families with high grocery, streaming, transit, and gas spending.",
    annualFee: "Paid annual fee",
    creditProfile: "Good to excellent credit usually expected",
    rewardStyle: "Cashback",
    highlights: ["US supermarket rewards", "Streaming rewards", "Transit and gas rewards", "Statement credit cashback"],
    pros: ["Strong everyday categories", "Easy cashback", "Good family spending fit"],
    cons: ["Annual fee", "Category caps may apply", "Amex acceptance varies"],
    criteria: ["You spend enough in eligible categories", "Cashback beats travel points for you", "You pay in full"],
    howToUse: ["Use for groceries and streaming", "Check category caps", "Pair with flat-rate card"],
    avoidIf: "Your grocery spend is low or mostly at excluded merchants.",
    sourceUrl: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    color: "from-blue-900 to-cyan-500"
  },
  {
    name: "Citi Double Cash",
    issuer: "Citi",
    country: "USA",
    type: "Credit",
    network: "Mastercard",
    slug: "citi-double-cash",
    bestFor: "Simple flat-rate cashback with minimal category management.",
    annualFee: "No annual fee",
    creditProfile: "Good credit usually expected",
    rewardStyle: "Flat-rate cashback",
    highlights: ["Simple cashback", "No annual fee", "Good catch-all card", "Can pair with Citi points cards"],
    pros: ["Easy to understand", "Good everyday baseline", "No annual fee"],
    cons: ["Few premium perks", "No category upside", "Foreign transaction terms should be checked"],
    criteria: ["You want simplicity", "Your spending is spread out", "You do not need travel perks"],
    howToUse: ["Use for non-bonus spending", "Pair with category cards", "Redeem consistently"],
    avoidIf: "You want travel insurance or premium card perks.",
    sourceUrl: "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
    color: "from-sky-950 to-blue-500"
  },
  {
    name: "Citi Custom Cash",
    issuer: "Citi",
    country: "USA",
    type: "Credit",
    network: "Mastercard",
    slug: "citi-custom-cash",
    bestFor: "One high monthly category such as groceries, gas, dining, or transit.",
    annualFee: "No annual fee",
    creditProfile: "Good credit usually expected",
    rewardStyle: "Adaptive category cashback",
    highlights: ["Top eligible spend category rewards", "No annual fee", "Simple monthly optimization"],
    pros: ["Automatically adapts to top category", "Useful as second card", "No annual fee"],
    cons: ["Bonus cap", "Only one top category", "Less useful for scattered spending"],
    criteria: ["You have one predictable monthly category", "You can monitor caps", "You want no annual fee"],
    howToUse: ["Assign one category role", "Stop after bonus cap", "Use flat-rate card after cap"],
    avoidIf: "You want all spending on one card.",
    sourceUrl: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    color: "from-indigo-950 to-violet-600"
  },
  {
    name: "Wells Fargo Active Cash",
    issuer: "Wells Fargo",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "wells-fargo-active-cash",
    bestFor: "Flat cashback on everyday purchases.",
    annualFee: "No annual fee",
    creditProfile: "Good credit usually expected",
    rewardStyle: "Flat-rate cashback",
    highlights: ["Flat cashback", "No annual fee", "Simple redemption", "Everyday card role"],
    pros: ["Easy rewards", "No category tracking", "Good first cashback upgrade"],
    cons: ["Limited premium travel benefits", "No category boost", "Approval depends on profile"],
    criteria: ["You want one simple card", "You pay in full", "You prefer cashback"],
    howToUse: ["Use for all uncategorized purchases", "Set autopay", "Redeem regularly"],
    avoidIf: "You want premium travel rewards.",
    sourceUrl: "https://creditcards.wellsfargo.com/active-cash-credit-card/",
    color: "from-red-950 to-rose-600"
  },
  {
    name: "Wells Fargo Autograph",
    issuer: "Wells Fargo",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "wells-fargo-autograph",
    bestFor: "No-fee travel, dining, gas, transit, and streaming categories.",
    annualFee: "No annual fee",
    creditProfile: "Good credit usually expected",
    rewardStyle: "Category rewards",
    highlights: ["Travel rewards", "Dining rewards", "Gas/transit rewards", "No annual fee"],
    pros: ["Broad useful categories", "No annual fee", "Good starter travel card"],
    cons: ["Less premium than fee travel cards", "Transfer options may vary", "Requires category awareness"],
    criteria: ["You want no-fee travel categories", "You spend on transport/dining", "You value simplicity"],
    howToUse: ["Use for travel/dining/transit", "Pair with flat cashback card", "Check redemption options"],
    avoidIf: "You want luxury lounge benefits.",
    sourceUrl: "https://creditcards.wellsfargo.com/autograph-visa-credit-card/",
    color: "from-orange-900 to-yellow-500"
  },
  {
    name: "Discover it Cash Back",
    issuer: "Discover",
    country: "USA",
    type: "Credit",
    network: "Discover",
    slug: "discover-it-cash-back",
    bestFor: "Rotating category cashback users who do not mind quarterly activation.",
    annualFee: "No annual fee",
    creditProfile: "Fair to good credit may qualify",
    rewardStyle: "Rotating category cashback",
    highlights: ["Quarterly bonus categories", "No annual fee", "Cashback match style intro feature", "Useful credit tools"],
    pros: ["High category upside", "No annual fee", "Good for active optimizers"],
    cons: ["Activation required", "Category caps", "Discover acceptance can vary abroad"],
    criteria: ["You track quarterly categories", "You can shift spending", "You prefer cashback"],
    howToUse: ["Activate categories", "Use until cap", "Pair with flat-rate card"],
    avoidIf: "You want set-and-forget rewards.",
    sourceUrl: "https://www.discover.com/credit-cards/cash-back/it-card.html",
    color: "from-orange-700 to-amber-400"
  },
  {
    name: "Discover it Student Cash Back",
    issuer: "Discover",
    country: "USA",
    type: "Credit",
    network: "Discover",
    slug: "discover-it-student-cash-back",
    bestFor: "Students building credit while learning rewards discipline.",
    annualFee: "No annual fee",
    creditProfile: "Student or limited credit profile",
    rewardStyle: "Student cashback",
    highlights: ["Student-friendly approval path", "Rotating cashback categories", "No annual fee", "Credit score education"],
    pros: ["Good first card", "No annual fee", "Rewards while building history"],
    cons: ["Activation and caps", "High APR if carrying balance", "Acceptance varies internationally"],
    criteria: ["You are a student", "You can pay in full", "You want to build credit safely"],
    howToUse: ["Use for small recurring purchases", "Set autopay", "Keep utilization low"],
    avoidIf: "You may use it as borrowed income.",
    sourceUrl: "https://www.discover.com/credit-cards/student-credit-card/it-card.html",
    color: "from-orange-800 to-lime-500"
  },
  {
    name: "Bank of America Customized Cash",
    issuer: "Bank of America",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "bank-of-america-customized-cash",
    bestFor: "Cashback users who want to choose a preferred bonus category.",
    annualFee: "No annual fee",
    creditProfile: "Good credit usually expected",
    rewardStyle: "Selectable category cashback",
    highlights: ["Choice category", "Grocery/wholesale style categories", "No annual fee", "Preferred Rewards upside"],
    pros: ["Flexible category choice", "No annual fee", "Strong for bank relationship users"],
    cons: ["Caps apply", "Requires category management", "Best value may require relationship status"],
    criteria: ["You know your top category", "You monitor caps", "You may have eligible bank relationship"],
    howToUse: ["Select category monthly if needed", "Use for chosen category", "Pair with flat-rate card"],
    avoidIf: "You do not want to manage categories.",
    sourceUrl: "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/",
    color: "from-red-900 to-blue-700"
  },
  {
    name: "U.S. Bank Cash+",
    issuer: "U.S. Bank",
    country: "USA",
    type: "Credit",
    network: "Visa",
    slug: "us-bank-cash-plus",
    bestFor: "Cashback optimizers selecting niche household categories.",
    annualFee: "No annual fee",
    creditProfile: "Good credit usually expected",
    rewardStyle: "Selectable category cashback",
    highlights: ["Choose bonus categories", "No annual fee", "Useful utilities/streaming style categories", "Cashback"],
    pros: ["Niche category value", "No annual fee", "Good as a supplement card"],
    cons: ["Activation required", "Caps apply", "Not ideal as only card"],
    criteria: ["You have predictable bills", "You can activate categories", "You like optimization"],
    howToUse: ["Pick categories around bills", "Track quarterly choices", "Use a fallback card elsewhere"],
    avoidIf: "You want one simple card.",
    sourceUrl: "https://www.usbank.com/credit-cards/cash-plus-visa-signature-credit-card.html",
    color: "from-blue-950 to-red-700"
  },
  {
    name: "HDFC Bank Infinia",
    issuer: "HDFC Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "hdfc-infinia",
    bestFor: "High-income Indian travelers seeking premium rewards and luxury benefits.",
    annualFee: "Premium annual fee",
    creditProfile: "Invite or premium eligibility",
    rewardStyle: "Premium reward points",
    highlights: ["Premium travel rewards", "Airport lounge benefits", "Golf/lifestyle perks", "Concierge style benefits"],
    pros: ["High reward potential", "Premium travel fit", "Strong lifestyle package"],
    cons: ["Eligibility restrictive", "High fee", "Reward rules need careful reading"],
    criteria: ["You meet premium eligibility", "You travel often", "You redeem points at good value"],
    howToUse: ["Use for high-value categories", "Track caps and vouchers", "Redeem for travel value"],
    avoidIf: "You do not meet spend or relationship requirements.",
    sourceUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/infinia-credit-card",
    color: "from-black to-emerald-700"
  },
  {
    name: "HDFC Regalia Gold",
    issuer: "HDFC Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "hdfc-regalia-gold",
    bestFor: "Indian salaried professionals wanting travel and lifestyle benefits.",
    annualFee: "Paid annual fee",
    creditProfile: "Good income and credit profile",
    rewardStyle: "Reward points",
    highlights: ["Airport lounge benefits", "Milestone benefits", "Travel redemptions", "Lifestyle rewards"],
    pros: ["Balanced premium-lite card", "Good travel starter", "Milestone upside"],
    cons: ["Fee waiver needs spend", "Reward values vary", "Not pure cashback"],
    criteria: ["You travel domestically/internationally", "You can meet milestones", "You prefer points"],
    howToUse: ["Put milestone spending here", "Use lounge benefits", "Redeem through high-value channels"],
    avoidIf: "You prefer direct cashback.",
    sourceUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card",
    color: "from-amber-700 to-yellow-300"
  },
  {
    name: "SBI Cashback Card",
    issuer: "SBI Card",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "sbi-cashback-card",
    bestFor: "Indian online shoppers who want straightforward cashback.",
    annualFee: "Paid annual fee",
    creditProfile: "Good credit profile",
    rewardStyle: "Cashback",
    highlights: ["Online cashback focus", "Simple statement cashback", "Good e-commerce fit"],
    pros: ["Simple value", "Strong online shopping use case", "Easy to understand"],
    cons: ["Caps/exclusions apply", "Offline value lower", "Fee waiver rules matter"],
    criteria: ["You shop online often", "You understand excluded categories", "You pay in full"],
    howToUse: ["Use for online purchases", "Check monthly caps", "Avoid excluded transactions"],
    avoidIf: "Most spending is offline or excluded.",
    sourceUrl: "https://www.sbicard.com/en/personal/credit-cards/rewards/cashback-sbi-card.page",
    color: "from-sky-900 to-cyan-400"
  },
  {
    name: "Axis Bank Atlas",
    issuer: "Axis Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "axis-bank-atlas",
    bestFor: "Indian travelers collecting airline/hotel transfer-style rewards.",
    annualFee: "Paid annual fee",
    creditProfile: "Good to premium credit profile",
    rewardStyle: "Travel edge miles style rewards",
    highlights: ["Travel-focused rewards", "Tiered benefits", "Airport lounge use", "Partner redemptions"],
    pros: ["Good travel orientation", "Milestone tiers", "International travel fit"],
    cons: ["Rules can be complex", "Annual fee", "Best for frequent travelers"],
    criteria: ["You travel often", "You can use partner redemptions", "You track tier rules"],
    howToUse: ["Use for travel spends", "Monitor tier milestones", "Redeem for partner value"],
    avoidIf: "You want simple cashback.",
    sourceUrl: "https://www.axisbank.com/retail/cards/credit-card/axis-bank-atlas-credit-card",
    color: "from-purple-950 to-fuchsia-600"
  },
  {
    name: "Amazon Pay ICICI Bank Credit Card",
    issuer: "ICICI Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "amazon-pay-icici",
    bestFor: "Amazon India users who want no-fee shopping rewards.",
    annualFee: "No annual fee",
    creditProfile: "Good credit profile",
    rewardStyle: "Amazon Pay cashback/rewards",
    highlights: ["Amazon shopping rewards", "No annual fee", "Simple redemption", "Useful for Prime users"],
    pros: ["No annual fee", "Strong Amazon fit", "Automatic reward style"],
    cons: ["Best value tied to Amazon ecosystem", "Other categories lower", "Eligibility varies"],
    criteria: ["You shop on Amazon frequently", "You want no annual fee", "You pay in full"],
    howToUse: ["Use for Amazon purchases", "Pair with another offline card", "Track reward crediting"],
    avoidIf: "You rarely use Amazon India.",
    sourceUrl: "https://www.icicibank.com/personal-banking/cards/credit-card/amazon-pay-credit-card",
    color: "from-slate-900 to-orange-500"
  },
  {
    name: "IDFC FIRST Wealth",
    issuer: "IDFC FIRST Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "idfc-first-wealth",
    bestFor: "Indian users wanting lifestyle perks with no joining/annual fee positioning.",
    annualFee: "Often positioned as lifetime free; verify current terms",
    creditProfile: "Good to premium credit profile",
    rewardStyle: "Reward points and lifestyle benefits",
    highlights: ["Lifestyle benefits", "Airport lounge benefits", "Reward points", "Low forex markup positioning may apply"],
    pros: ["Useful perk bundle", "Travel/lifestyle fit", "Good if no fee terms apply"],
    cons: ["Eligibility varies", "Reward value needs checking", "Terms can change"],
    criteria: ["You qualify for the variant", "You use lifestyle benefits", "You verify current fees"],
    howToUse: ["Use for eligible categories", "Check lounge rules", "Review forex and fee schedule"],
    avoidIf: "You cannot verify the latest fee and benefit terms.",
    sourceUrl: "https://www.idfcfirstbank.com/credit-card/wealth",
    color: "from-red-950 to-amber-600"
  },
  {
    name: "ICICI Bank Sapphiro",
    issuer: "ICICI Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "icici-bank-sapphiro",
    bestFor: "Indian professionals who want airport lounge, movies, dining, and lifestyle benefits in one card.",
    annualFee: "Paid annual fee or relationship-based offers; verify current terms",
    creditProfile: "Good to premium credit profile",
    rewardStyle: "Reward points and lifestyle benefits",
    highlights: ["Airport lounge benefits", "Movie ticket offers", "Dining privileges", "Travel and lifestyle rewards"],
    pros: ["Broad lifestyle package", "Good for urban professionals", "Useful bank ecosystem"],
    cons: ["Reward value can be complex", "Fees vary by offer", "Benefits require tracking"],
    criteria: ["You use travel and dining benefits", "You can verify fee waiver terms", "You prefer bank ecosystem cards"],
    howToUse: ["Use for lifestyle categories", "Track lounge and movie rules", "Compare point redemption value"],
    avoidIf: "You want direct simple cashback with no benefit tracking.",
    sourceUrl: "https://www.icicibank.com/personal-banking/cards/credit-card/sapphiro-credit-card",
    color: "from-orange-900 to-rose-600"
  },
  {
    name: "ICICI Bank Coral",
    issuer: "ICICI Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "icici-bank-coral",
    bestFor: "Entry-level Indian credit card users wanting basic rewards and lifestyle offers.",
    annualFee: "Low to moderate fee; verify current terms",
    creditProfile: "Entry to good credit profile",
    rewardStyle: "Reward points",
    highlights: ["Basic rewards", "Movie and dining offers", "Fuel surcharge waiver style benefit", "Bank offers"],
    pros: ["Accessible card tier", "Useful starter benefits", "Good for learning credit discipline"],
    cons: ["Lower reward value than premium cards", "Fee waiver rules matter", "Limited premium travel perks"],
    criteria: ["You are building card history", "You want basic offers", "You pay in full"],
    howToUse: ["Use for small planned spends", "Watch statement due dates", "Check reward redemption minimums"],
    avoidIf: "You need premium travel or high cashback.",
    sourceUrl: "https://www.icicibank.com/personal-banking/cards/credit-card/coral-credit-card",
    color: "from-rose-800 to-orange-400"
  },
  {
    name: "Axis Bank ACE",
    issuer: "Axis Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "axis-bank-ace",
    bestFor: "Indian users wanting utility bill and everyday cashback-style value.",
    annualFee: "Paid annual fee",
    creditProfile: "Good credit profile",
    rewardStyle: "Cashback",
    highlights: ["Utility payment value", "Everyday cashback", "Food delivery style offers", "Simple statement value"],
    pros: ["Useful for bills", "Cashback is easier than points", "Good everyday card role"],
    cons: ["Caps and exclusions apply", "Terms changed historically in many card markets", "Not a luxury travel card"],
    criteria: ["You pay recurring bills by card", "You monitor caps", "You want cash value"],
    howToUse: ["Use for eligible bills", "Check monthly caps", "Pair with travel card if needed"],
    avoidIf: "Your spending is mostly excluded categories.",
    sourceUrl: "https://www.axisbank.com/retail/cards/credit-card/axis-bank-ace-credit-card",
    color: "from-red-950 to-pink-500"
  },
  {
    name: "Axis Bank Magnus",
    issuer: "Axis Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "axis-bank-magnus",
    bestFor: "High-spend Indian users who can evaluate premium points, milestones, and travel benefits carefully.",
    annualFee: "Premium annual fee",
    creditProfile: "Premium credit profile",
    rewardStyle: "Premium reward points",
    highlights: ["Premium rewards", "Travel benefits", "Milestone benefits", "Lifestyle privileges"],
    pros: ["Strong high-spend potential", "Premium travel positioning", "Milestone upside"],
    cons: ["Complex rules", "High fee", "Devaluation risk in reward programs"],
    criteria: ["You have high eligible monthly spend", "You track benefit changes", "You redeem points intelligently"],
    howToUse: ["Calculate net annual value", "Track milestone terms", "Avoid low-value redemptions"],
    avoidIf: "You dislike changing card terms or benefit complexity.",
    sourceUrl: "https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-credit-card",
    color: "from-zinc-950 to-purple-700"
  },
  {
    name: "SBI Card ELITE",
    issuer: "SBI Card",
    country: "India",
    type: "Credit",
    network: "Mastercard",
    slug: "sbi-card-elite",
    bestFor: "Indian users wanting lifestyle, movies, lounge access, and milestone rewards.",
    annualFee: "Paid annual fee",
    creditProfile: "Good to premium credit profile",
    rewardStyle: "Reward points and vouchers",
    highlights: ["Welcome voucher style benefits", "Movie benefits", "Lounge access", "Milestone rewards"],
    pros: ["Broad lifestyle benefits", "Good for entertainment spenders", "Strong SBI Card ecosystem"],
    cons: ["Fee is meaningful", "Voucher value depends on usage", "Rewards need redemption planning"],
    criteria: ["You use movie and lifestyle perks", "You can meet milestone spends", "You pay in full"],
    howToUse: ["Track vouchers", "Use lounge benefits", "Redeem points before expiry"],
    avoidIf: "You prefer no-fee cashback.",
    sourceUrl: "https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-elite.page",
    color: "from-slate-950 to-blue-600"
  },
  {
    name: "SBI SimplyCLICK",
    issuer: "SBI Card",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "sbi-simplyclick",
    bestFor: "Indian online shoppers who want an entry-level rewards card for e-commerce.",
    annualFee: "Low annual fee",
    creditProfile: "Entry to good credit profile",
    rewardStyle: "Online rewards",
    highlights: ["Online shopping rewards", "Milestone e-voucher style benefits", "Low fee", "E-commerce partner offers"],
    pros: ["Accessible online card", "Useful for beginners", "Low fee compared with premium cards"],
    cons: ["Limited premium perks", "Partner categories matter", "Offline value may be lower"],
    criteria: ["You shop online frequently", "You want a starter card", "You understand partner rules"],
    howToUse: ["Use for eligible online partners", "Track milestone vouchers", "Avoid cash withdrawals"],
    avoidIf: "You need travel perks or high offline rewards.",
    sourceUrl: "https://www.sbicard.com/en/personal/credit-cards/rewards/simplyclick-sbi-card.page",
    color: "from-blue-950 to-cyan-500"
  },
  {
    name: "Kotak League Platinum",
    issuer: "Kotak Mahindra Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "kotak-league-platinum",
    bestFor: "Indian users wanting a mid-tier rewards card for everyday spending and milestone value.",
    annualFee: "Fee varies; verify current terms",
    creditProfile: "Good credit profile",
    rewardStyle: "Reward points",
    highlights: ["Everyday reward points", "Milestone benefits", "Bank offers", "Lifestyle redemption"],
    pros: ["Mid-tier everyday card", "Milestone potential", "Useful Kotak relationship fit"],
    cons: ["Not a top-tier travel card", "Reward value varies", "Terms need verification"],
    criteria: ["You bank with Kotak", "You want everyday rewards", "You track redemption value"],
    howToUse: ["Use for eligible spends", "Review reward catalogue", "Check fee waiver conditions"],
    avoidIf: "You want transparent flat cashback.",
    sourceUrl: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
    color: "from-red-900 to-blue-900"
  },
  {
    name: "IndusInd Bank Legend",
    issuer: "IndusInd Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "indusind-bank-legend",
    bestFor: "Indian users wanting lifestyle, travel, and weekend reward-style benefits.",
    annualFee: "Fee/offer terms vary",
    creditProfile: "Good to premium credit profile",
    rewardStyle: "Reward points and lifestyle benefits",
    highlights: ["Lifestyle offers", "Travel benefits", "Reward points", "Concierge-style positioning"],
    pros: ["Premium-lite positioning", "Useful lifestyle bundle", "Good for bank relationship users"],
    cons: ["Benefit value varies", "Terms require checking", "Not pure cashback"],
    criteria: ["You use lifestyle benefits", "You verify latest fee terms", "You prefer rewards over cashback"],
    howToUse: ["Use for benefit categories", "Track weekend/reward rules", "Review redemption value"],
    avoidIf: "You want simple uncapped cashback.",
    sourceUrl: "https://www.indusind.com/in/en/personal/cards/credit-card.html",
    color: "from-stone-950 to-amber-600"
  },
  {
    name: "AU Bank Zenith+",
    issuer: "AU Small Finance Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "au-bank-zenith-plus",
    bestFor: "Indian premium card users comparing travel, dining, and lifestyle benefits outside large bank ecosystems.",
    annualFee: "Premium annual fee",
    creditProfile: "Good to premium credit profile",
    rewardStyle: "Premium rewards",
    highlights: ["Travel and dining benefits", "Reward points", "Lifestyle privileges", "Milestone features"],
    pros: ["Premium alternative", "Lifestyle value", "Potentially strong for targeted users"],
    cons: ["Fee is meaningful", "Acceptance/servicing experience should be evaluated", "Terms can vary"],
    criteria: ["You qualify for premium variant", "You use dining/travel benefits", "You compare against large-bank cards"],
    howToUse: ["Calculate annual net value", "Track milestones", "Use only if benefits fit real spending"],
    avoidIf: "You want a basic no-fee card.",
    sourceUrl: "https://www.aubank.in/personal-banking/credit-cards",
    color: "from-orange-900 to-yellow-500"
  },
  {
    name: "YES Bank Marquee",
    issuer: "YES Bank",
    country: "India",
    type: "Credit",
    network: "Mastercard",
    slug: "yes-bank-marquee",
    bestFor: "High-spend Indian users comparing premium reward points and travel privileges.",
    annualFee: "Premium annual fee",
    creditProfile: "Premium credit profile",
    rewardStyle: "Premium reward points",
    highlights: ["High reward positioning", "Travel benefits", "Lifestyle privileges", "Milestone value"],
    pros: ["Premium rewards potential", "Travel/lifestyle fit", "Useful for high spenders"],
    cons: ["High fee", "Reward value depends on redemption", "Issuer terms need close review"],
    criteria: ["You have high eligible spend", "You redeem points at strong value", "You track fee waiver or milestone rules"],
    howToUse: ["Use for high-value categories", "Calculate redemption value", "Review benefit changes annually"],
    avoidIf: "You do not want premium card complexity.",
    sourceUrl: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
    color: "from-blue-950 to-sky-500"
  },
  {
    name: "Federal Bank Scapia",
    issuer: "Federal Bank",
    country: "India",
    type: "Credit",
    network: "Visa",
    slug: "federal-bank-scapia",
    bestFor: "Indian travelers looking for app-led travel rewards and low forex-markup positioning.",
    annualFee: "Verify current fee terms",
    creditProfile: "Good credit profile",
    rewardStyle: "Travel rewards",
    highlights: ["Travel app ecosystem", "Forex-focused positioning", "Travel rewards", "Digital-first experience"],
    pros: ["Modern travel UX", "Good for international travelers", "Simple app-led value"],
    cons: ["Terms and availability can change", "App ecosystem dependency", "Not ideal for offline cashback"],
    criteria: ["You travel internationally", "You value low forex costs", "You are comfortable with app-led rewards"],
    howToUse: ["Use for travel bookings", "Check forex terms before trips", "Track reward redemption inside app"],
    avoidIf: "You prefer traditional bank reward catalogues.",
    sourceUrl: "https://www.federalbank.co.in/credit-cards",
    color: "from-emerald-950 to-lime-500"
  },
  {
    name: "Barclaycard Avios Plus",
    issuer: "Barclays",
    country: "UK",
    type: "Credit",
    network: "Mastercard",
    slug: "barclaycard-avios-plus",
    bestFor: "UK travelers collecting Avios for British Airways and partner redemptions.",
    annualFee: "Paid monthly/annual-style fee; verify current terms",
    creditProfile: "Good UK credit profile",
    rewardStyle: "Avios",
    highlights: ["Avios earning", "Cabin upgrade voucher style benefit", "Travel rewards", "UK credit card use case"],
    pros: ["Strong Avios fit", "Good for BA travelers", "Travel reward clarity"],
    cons: ["Fee", "Avios value varies", "Not ideal for cashback seekers"],
    criteria: ["You collect Avios", "You can use voucher benefits", "You fly BA or partners"],
    howToUse: ["Use for everyday Avios earning", "Plan voucher redemption", "Compare Avios cash value"],
    avoidIf: "You do not use Avios.",
    sourceUrl: "https://www.barclaycard.co.uk/personal/credit-cards/avios-plus",
    color: "from-blue-950 to-sky-500"
  },
  {
    name: "British Airways American Express Premium Plus",
    issuer: "American Express UK",
    country: "UK",
    type: "Credit",
    network: "American Express",
    slug: "ba-amex-premium-plus",
    bestFor: "UK British Airways loyalists who can use companion voucher benefits.",
    annualFee: "Paid annual fee",
    creditProfile: "Good UK credit profile",
    rewardStyle: "Avios",
    highlights: ["Avios earning", "Companion voucher style benefit", "BA travel focus", "Amex offers"],
    pros: ["Strong BA fit", "Valuable voucher if used well", "Good for frequent BA users"],
    cons: ["Annual fee", "Amex acceptance varies", "Voucher value depends on redemption"],
    criteria: ["You fly BA", "You can meet spend threshold", "You understand Avios availability"],
    howToUse: ["Put BA and daily spend strategically", "Plan voucher routes early", "Avoid low-value redemptions"],
    avoidIf: "You rarely fly British Airways.",
    sourceUrl: "https://www.americanexpress.com/en-gb/credit-cards/ba-premium-plus-credit-card/",
    color: "from-blue-900 to-red-600"
  },
  {
    name: "Tesco Bank Clubcard Credit Card",
    issuer: "Tesco Bank",
    country: "UK",
    type: "Credit",
    network: "Mastercard",
    slug: "tesco-clubcard-credit-card",
    bestFor: "UK grocery shoppers who collect Tesco Clubcard points.",
    annualFee: "Usually no annual fee; verify current terms",
    creditProfile: "UK credit profile subject to approval",
    rewardStyle: "Retail loyalty points",
    highlights: ["Clubcard points", "Grocery ecosystem", "Everyday shopping rewards", "Retail redemption"],
    pros: ["Good Tesco shopper fit", "Simple loyalty rewards", "Useful everyday card"],
    cons: ["Best value tied to Tesco", "Not premium travel", "APR matters if carrying balance"],
    criteria: ["You shop at Tesco", "You collect Clubcard points", "You pay in full"],
    howToUse: ["Use for Tesco spend", "Stack with Clubcard offers", "Avoid interest"],
    avoidIf: "You do not shop at Tesco.",
    sourceUrl: "https://www.tescobank.com/credit-cards/",
    color: "from-blue-800 to-red-500"
  }
];

export const debitCards: CardProduct[] = [
  {
    name: "Chase Secure Banking Debit Card",
    issuer: "Chase",
    country: "USA",
    type: "Debit",
    network: "Visa",
    slug: "chase-secure-banking-debit",
    bestFor: "US users wanting predictable banking with debit access and no overdraft surprise positioning.",
    annualFee: "Monthly account fee may apply",
    creditProfile: "No credit line",
    rewardStyle: "Debit access",
    highlights: ["Debit card access", "Budget control", "Mobile banking", "No revolving debt"],
    pros: ["No credit card debt", "Good for spending discipline", "Bank branch/app ecosystem"],
    cons: ["May have account fee", "Fewer rewards", "Debit fraud protections differ from credit"],
    criteria: ["You want spending from available cash", "You do not need credit building", "You value predictable account rules"],
    howToUse: ["Use for budgeted spending", "Keep alerts on", "Maintain emergency cash elsewhere"],
    avoidIf: "You need to build credit or want strong card rewards.",
    sourceUrl: "https://www.chase.com/personal/secure-banking",
    color: "from-blue-950 to-cyan-600"
  },
  {
    name: "Capital One 360 Checking Debit Card",
    issuer: "Capital One",
    country: "USA",
    type: "Debit",
    network: "Mastercard",
    slug: "capital-one-360-debit",
    bestFor: "Digital-first US checking users who want app-first banking and debit access.",
    annualFee: "Account fees vary; verify current terms",
    creditProfile: "No credit line",
    rewardStyle: "Debit access",
    highlights: ["Digital checking", "Debit purchases", "ATM access", "No credit borrowing"],
    pros: ["Simple spending control", "Good online banking fit", "No revolving balance"],
    cons: ["Limited rewards", "Checking-account rules matter", "Not a credit builder"],
    criteria: ["You prefer digital banking", "You use debit for essentials", "You want cash-flow control"],
    howToUse: ["Separate bills and spending", "Use alerts", "Keep debit card locked when not needed"],
    avoidIf: "You want rewards and credit history building.",
    sourceUrl: "https://www.capitalone.com/bank/checking-accounts/online-checking-account/",
    color: "from-red-900 to-blue-700"
  },
  {
    name: "HDFC Bank EasyShop Platinum Debit Card",
    issuer: "HDFC Bank",
    country: "India",
    type: "Debit",
    network: "Visa",
    slug: "hdfc-easyshop-platinum-debit",
    bestFor: "Indian account holders who want everyday debit usage with bank-linked benefits.",
    annualFee: "Account/card fees vary",
    creditProfile: "No credit line",
    rewardStyle: "Debit rewards/benefits",
    highlights: ["ATM access", "Shopping payments", "Bank account linked", "Potential reward points/insurance benefits"],
    pros: ["No borrowing", "Works for daily payments", "Good for account holders"],
    cons: ["Fees and limits vary", "Rewards usually lower than credit", "Does not build credit"],
    criteria: ["You bank with HDFC", "You want debit control", "You verify limits and charges"],
    howToUse: ["Use for cash-flow spending", "Set transaction limits", "Use UPI/cards depending on merchant"],
    avoidIf: "You want premium credit rewards.",
    sourceUrl: "https://www.hdfcbank.com/personal/pay/cards/debit-cards",
    color: "from-blue-950 to-sky-500"
  },
  {
    name: "SBI Global International Debit Card",
    issuer: "State Bank of India",
    country: "India",
    type: "Debit",
    network: "Visa",
    slug: "sbi-global-international-debit",
    bestFor: "SBI customers needing wide debit acceptance and ATM access.",
    annualFee: "Card/account fees vary",
    creditProfile: "No credit line",
    rewardStyle: "Debit access",
    highlights: ["ATM withdrawals", "Merchant payments", "International acceptance variant", "Bank-linked security"],
    pros: ["Wide SBI ecosystem", "No debt", "Useful for daily banking"],
    cons: ["Charges/limits vary", "FX markup may apply", "Limited rewards"],
    criteria: ["You hold SBI account", "You need ATM/debit access", "You check international fees"],
    howToUse: ["Use spending alerts", "Set international usage only when needed", "Protect PIN and card controls"],
    avoidIf: "You need credit card-style rewards and protections.",
    sourceUrl: "https://sbi.co.in/web/personal-banking/cards/debit-card",
    color: "from-sky-900 to-blue-400"
  },
  {
    name: "Monzo Debit Card",
    issuer: "Monzo",
    country: "UK",
    type: "Debit",
    network: "Mastercard",
    slug: "monzo-debit-card",
    bestFor: "UK app-first budgeting with pots, alerts, and spending visibility.",
    annualFee: "Account plan fees vary",
    creditProfile: "No credit line",
    rewardStyle: "Budgeting features",
    highlights: ["Instant notifications", "Budgeting pots", "App controls", "Debit spending"],
    pros: ["Excellent spending visibility", "Good budgeting UX", "No credit debt"],
    cons: ["Not a rewards credit card", "Paid tiers vary", "Cash deposit rules may matter"],
    criteria: ["You want budgeting tools", "You prefer app banking", "You use debit intentionally"],
    howToUse: ["Create pots for bills", "Use alerts", "Freeze card from app if misplaced"],
    avoidIf: "You need credit building or premium rewards.",
    sourceUrl: "https://monzo.com/",
    color: "from-pink-600 to-orange-400"
  },
  {
    name: "Starling Bank Debit Card",
    issuer: "Starling Bank",
    country: "UK",
    type: "Debit",
    network: "Mastercard",
    slug: "starling-bank-debit-card",
    bestFor: "UK digital banking users who want clean app controls and travel-friendly debit usage.",
    annualFee: "Account fees vary by product",
    creditProfile: "No credit line",
    rewardStyle: "Budgeting and banking features",
    highlights: ["Spaces/budgeting", "Debit payments", "App controls", "Travel-friendly positioning"],
    pros: ["Strong digital banking", "Good spending controls", "No revolving debt"],
    cons: ["Limited rewards", "No credit history building", "Product terms vary"],
    criteria: ["You prefer app banking", "You need debit control", "You want clear spending categories"],
    howToUse: ["Use spaces for goals", "Review spending analytics", "Keep notifications on"],
    avoidIf: "You want credit card protections and rewards.",
    sourceUrl: "https://www.starlingbank.com/current-account/",
    color: "from-teal-800 to-emerald-400"
  }
];

export const allCards = [...creditCards.map(enrichCard), ...debitCards];

export function enrichCard(card: CardProduct): CardProduct {
  if (card.type !== "Credit") return card;
  const lower = `${card.bestFor} ${card.rewardStyle} ${card.highlights.join(" ")}`.toLowerCase();
  const travel = lower.includes("travel") || lower.includes("lounge") || lower.includes("miles") || lower.includes("avios");
  const cashback = lower.includes("cashback") || lower.includes("cash");
  const shopping = lower.includes("shopping") || lower.includes("amazon") || lower.includes("online");

  return {
    ...card,
    earnGuide:
      card.earnGuide ??
      (travel
        ? [
            "Put travel bookings, eligible dining, and issuer-bonus categories on the card only when you can pay in full.",
            "Track milestone spends monthly instead of rushing purchases near the deadline.",
            "Avoid low-value transactions such as cash withdrawals, wallet loads, rent payments, or excluded categories unless terms clearly reward them."
          ]
        : cashback
          ? [
              "Use the card only for categories where cashback is clearly eligible.",
              "Watch monthly or quarterly caps so you do not assume the headline rate applies forever.",
              "Pair it with a flat-rate card once category caps or exclusions begin."
            ]
          : [
              "Use the card for planned purchases that match its reward categories.",
              "Review the issuer reward catalogue before chasing points.",
              "Keep utilization low and pay the statement balance every cycle."
            ]),
    redeemGuide:
      card.redeemGuide ??
      (travel
        ? [
            "Compare flight, hotel, statement credit, voucher, and transfer-partner redemption values before using points.",
            "Redeem early enough to avoid award-seat scarcity, blackout dates, or voucher expiry.",
            "Use points where they replace a trip you already wanted, not where they create unnecessary travel."
          ]
        : cashback
          ? [
              "Prefer statement credit or direct cashback when available and easy to value.",
              "Redeem before rewards expire or rules change.",
              "Do not spend extra to earn cashback; net savings matter more than reward percentage."
            ]
          : [
              "Check whether points have different values for vouchers, travel, products, or statement credits.",
              "Avoid merchandise redemptions if they produce weak value.",
              "Set a calendar reminder for reward expiry and milestone voucher deadlines."
            ]),
    bestSpendingPlaces:
      card.bestSpendingPlaces ??
      (shopping
        ? ["E-commerce purchases", "Eligible partner merchants", "Planned festival-sale purchases", "Subscription renewals if rewarded"]
        : travel
          ? ["Flights and hotels", "Dining while travelling", "Foreign currency transactions when markup is favorable", "Travel insurance eligible bookings"]
          : cashback
            ? ["Groceries", "Fuel or transport if eligible", "Utilities if rewarded", "Everyday retail spends"]
            : ["Dining", "Groceries", "Recurring bills", "Issuer offer merchants"])
  };
}

export function getCard(slug: string) {
  const card = allCards.find((item) => item.slug === slug);
  return card ? enrichCard(card) : undefined;
}

export function getCardsByType(type: "Credit" | "Debit") {
  return allCards.filter((card) => card.type === type).map(enrichCard);
}
